version: '3.9'

services:
  jobqueue-api:
    build: .
    container_name: jobqueue_api
    command: ["sh", "-c", "node dist/db/migrate.js && node dist/api/server.js"]
    environment:
      NODE_ENV: production
      PORT: 3000
      API_KEY: default-dev-key
      FRONTEND_URL: http://localhost:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jobqueue
      DB_USER: postgres
      DB_PASSWORD: postgres
      WORKER_CONCURRENCY: 5
      MAX_RETRY_ATTEMPTS: 3
      RETRY_DELAY_MS: 1000
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres

  jobqueue-worker:
    build: .
    container_name: jobqueue_worker
    command: ["sh", "-c", "node dist/db/migrate.js && node dist/queue/workers/workerPool.js"]
    environment:
      NODE_ENV: production
      PORT: 3000
      API_KEY: default-dev-key
      FRONTEND_URL: http://localhost:3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jobqueue
      DB_USER: postgres
      DB_PASSWORD: postgres
      WORKER_CONCURRENCY: 5
      MAX_RETRY_ATTEMPTS: 3
      RETRY_DELAY_MS: 1000
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: jobqueue_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: jobqueue_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: jobqueue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: jobqueue_redis_ui
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: jobqueue_prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: jobqueue_grafana
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data: